#!/usr/bin/env bash

# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

# Get path of the oelldb script
# See https://mywiki.wooledge.org/BashFAQ/028 for complexities involved
# in determining location of a bash script. ${BASH_SOURCE}, though not perfect,
# is an acceptable solution for oelldb.
# readlink provides additional benefit in getting the absolute path
# to the script directory for systems where BASH_SOURCE is only relative.
OE_LLDB_DIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")

OE_LLDB_LIB_DIR=$OE_LLDB_DIR


OE_LLDB_PLUGIN_DIR=$OE_LLDB_LIB_DIR
OE_LLDB_PTRACE_PATH=$OE_LLDB_LIB_DIR/liboe_ptrace.so

export PYTHONPATH=$OE_LLDB_PLUGIN_DIR
export LD_PRELOAD=$OE_LLDB_PTRACE_PATH
lldb -o "command script import oelldb" "$@"
